# Generated by Django 5.1.5 on 2025-01-19 23:27

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="stockquote",
            managers=[
                ("timescale", django.db.models.manager.Manager()),
            ],
        ),
    ]
