# Generated by Django 5.1.5 on 2025-01-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_alter_stockquote_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="stockquote",
            managers=[],
        ),
    ]
