# Generated by Django 5.1.5 on 2025-01-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_stockquote_managers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stockquote",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="stockquote",
            name="raw_timestamp",
            field=models.CharField(
                blank=True,
                help_text="Non-transformed timestamp string or int/float.",
                max_length=120,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="stockquote",
            constraint=models.UniqueConstraint(
                fields=("company", "time"), name="unique_company_time"
            ),
        ),
    ]
