# Generated by Django 5.1.5 on 2025-01-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0006_alter_stockquote_raw_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockquote",
            name="ema",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stockquote",
            name="macd",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stockquote",
            name="rsi",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stockquote",
            name="sma",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
